include: all_lint_rules.yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    included_file_warning: ignore

linter:
  rules:
    cascade_invocations: true
    prefer_double_quotes: false
    always_specify_types: false
    unnecessary_final: false
    prefer_expression_function_bodies: false
    always_put_required_named_parameters_first: false
    lines_longer_than_80_chars: false
    no_default_cases: false
    public_member_api_docs: false
    diagnostic_describe_all_properties: false
    avoid_classes_with_only_static_members: false
    prefer_relative_imports: false
    avoid_types_on_closure_parameters: false
    avoid_final_parameters: false