name: calm_mind
description: A new Flutter project.
version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=2.12.0-0 <3.0.0"
dependencies:
  bloc: ^7.0.0
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^0.21.0+1
  google_fonts: ^2.0.0
  intl: ^0.17.0
dev_dependencies:
  bloc_test: ^8.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.1
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
